name: Docker Image CI

on: # 조건(트리거)
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v3

# jdk 11 세팅
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

# 패키징
    - name: Build with Maven
      run: mvn -B package --file pom.xml

# 도커 로그인
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

# 도커 이미지 빌드
    - name: Build the Docker image
      run: docker build -t jangmin063/inkbridge-gateway .
      
# 이미지 띄우기
    - name: push Docker image
      run: docker push jangmin063/inkbridge-gateway
      
# 쉘 스크립트 실행
    - name: execute shell script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_IP }}         # 인스턴스 플로팅 ip
        username: ${{ secrets.SSH_ID }}     # user Id(testuser같은거)
        key: ${{ secrets.SSH_KEY }}         # user 개인키 <- begin부터 end까지 다
        port: ${{ secrets.SSH_PORT }}       # ssh 포트 = 22
        script_stop: true
        script: "./startup.sh"
